pipeline:
  build:
    image: node
    commands:
      - npm --version
  whatever:
    image: alpine
    commands:
      - echo ${DRONE_REPO} ${DRONE_BRANCH} ${DRONE_PULL_REQUEST} ${SEC1}
      - echo Done!
  publish:
    image: plugins/docker
    repo: ivankravchenko/test-drone
    tags: [ latest, 1, 1.0, 1.0.0 ]
    when:
      branch: master
      event: push
