pipeline:
  build:
    image: node
    commands:
      - npm --version
  whatever:
    image: alpine
    commands:
      - echo Done!
  publish:
    image: plugins/docker
    repo: ivankravchenko/test-drone
    tags: [ latest, 1, 1.0, 1.0.0 ]
